site_name: XMUX Help

repo_url: https://github.com/XMUMY/docs
site_description: XMUX Help Center
copyright: Copytight Â© 2019 XMUX Project. All rights reserved.

nav:
  - Home: index.md
  - Application:
      - Get Started: app/get-started.md
      - Online Attendance: app/online-attendance.md
  - Campus:
      - Links: campus/links.md
      - About: campus/about.md
  - Developer:
      - Architecture: developer/architecture.md
      - CLA: developer/cla.md
      - Contributors: developer/contributors.md

theme:
  name: material
  feature:
    tabs: true

markdown_extensions:
  - admonition
